version: '3.8'
services:
  api: 
    build: ./api
    container_name: mge-scheduler-api
    ports:
      - '8080:8080'
    volumes:
      - ./api:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: mge-scheduler-client
    ports: 
      - 3000:3000
    stdin_open: true
    tty: true
